export default function Head() {
  return (
    <>
      <title>Prontuário Eletrônico</title>
      <meta name="description" content="Generated by IESB" />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="./icon/prancheta.png"
      />
    </>
  );
}
