"use client";
import Menu from "@/components/Menu";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthContext, { AuthContextProvider } from "@/state/authContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//title: "Prontuario Eletrônico",
//description: "Generated by IESB",
//};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <head />
      <body className={inter.className}>
        <Menu />
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
