import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Prontuario Eletrônico',
  description: 'Generated by IESB',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" type='image/png' sizes='16x16' href='./icon/prancheta.png' />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}